### ISSUE TITLE
I replaced the weight file，add parser.add_argument('--yolo_weights', type=str, default='yolov5/weights/yolov5m6.pt'in the track.py help='yolov5m6.pt path') 

### ISSUE THREAD

**Issue by xurui-maker** [mikel-brostrom/Yolov5_DeepSort_OSNet#385]
Fusing layers...
YOLOv5m6 summary: 481 layers, 35731932 parameters, 0 gradients, 50.1 GFLOPs
Traceback (most recent call last):
  File "D:\Yolov5_DeepSort_OSNet-3.0\track.py", line 295, in <module>
    detect(args)
  File "D:\Yolov5_DeepSort_OSNet-3.0\track.py", line 160, in detect
    for frame_idx, (path, img, im0s, vid_cap) in enumerate(dataset):
ValueError: too many values to unpack (expected 4)

**Comment by mikel-brostrom** [comment]
I don't own a Windows computer. Maybe somebody else could help out here...
