### ISSUE TITLE
 failed finding central directory

### ISSUE THREAD

**Issue by qq1243196045** [mikel-brostrom/Yolov5_DeepSort_OSNet#402]
(deep) white@ubuntu18-white:~/projects/python/Yolov5_DeepSort_OSNet$ python track.py --source 0
deep_sort/deep/reid/torchreid/metrics/rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '

Available ReID models for automatic download
['resnet50_market1501', 'resnet50_dukemtmcreid', 'resnet50_msmt17', 'resnet50_fc512_market1501', 'resnet50_fc512_dukemtmcreid', 'resnet50_fc512_msmt17', 'mlfn_market1501', 'mlfn_dukemtmcreid', 'mlfn_msmt17', 'hacnn_market1501', 'hacnn_dukemtmcreid', 'hacnn_msmt17', 'mobilenetv2_x1_0_market1501', 'mobilenetv2_x1_0_dukemtmcreid', 'mobilenetv2_x1_0_msmt17', 'mobilenetv2_x1_4_market1501', 'mobilenetv2_x1_4_dukemtmcreid', 'mobilenetv2_x1_4_msmt17', 'osnet_x1_0_market1501', 'osnet_x1_0_dukemtmcreid', 'osnet_x1_0_msmt17', 'osnet_x0_75_market1501', 'osnet_x0_75_dukemtmcreid', 'osnet_x0_75_msmt17', 'osnet_x0_5_market1501', 'osnet_x0_5_dukemtmcreid', 'osnet_x0_5_msmt17', 'osnet_x0_25_market1501', 'osnet_x0_25_dukemtmcreid', 'osnet_x0_25_msmt17', 'resnet50_MSMT17', 'osnet_x1_0_MSMT17', 'osnet_x0_75_MSMT17', 'osnet_x0_5_MSMT17', 'osnet_x0_25_MSMT17', 'osnet_ibn_x1_0_MSMT17', 'osnet_ain_x1_0_MSMT17']
YOLOv5 🚀 v6.1-38-g7c6a335 torch 1.7.1+cu110 CUDA:0 (NVIDIA GeForce GTX 1060 6GB, 6075MiB)

w is yolov5m.pt
Traceback (most recent call last):
  File "track.py", line 289, in <module>
    detect(opt)
  File "track.py", line 73, in detect
    model = DetectMultiBackend(yolo_model, device=device, dnn=opt.dnn)
  File "/home/white/projects/python/Yolov5_DeepSort_OSNet/yolov5/models/common.py", line 306, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, map_location=device)
  File "./yolov5/models/experimental.py", line 97, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/home/white/anaconda3/envs/deep/lib/python3.7/site-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/white/anaconda3/envs/deep/lib/python3.7/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

I try install torch=1.7 and torch=1.11,They all have this bug,and I have already download  "yolov5m.pt" to yolov5_DeepSort_OSNet/yolov5m.pt,what should I do?

一开始我安装torch版本是1.11,报了这个错后我以为是版本太高了,于是我降到1.7,依旧有这个错,我怀疑这个yolov5m.pt文件不是zip格式文件(可能是torch1.6以下版本训练出来的文件?但是这个文件是直接下载好的,我不知道该怎么做)

**Comment by qq1243196045** [comment]
使用file指令查看文件格式:
 stat yolov5m.pt 
yolov5m.pt: Zip archive data

**Comment by qq1243196045** [comment]
IT'S OK!
I remove yolov5m.pt and re-run  python track.py --source 0
