### ISSUE TITLE
No module named 'utils.dataloaders'

### ISSUE THREAD

**Issue by Vananananana** [mikel-brostrom/Yolov5_DeepSort_OSNet#411]
Traceback (most recent call last):
  File "track.py", line 30, in <module>
    from yolov5.models.experimental import attempt_load
  File "/home/scu/Yolo/Yolov5_DeepSort_OSNet/yolov5/models/experimental.py", line 11, in <module>
    from models.common import Conv
  File "/home/scu/Yolo/Yolov5_DeepSort_OSNet/yolov5/models/common.py", line 24, in <module>
    from utils.dataloaders import exif_transpose, letterbox
ModuleNotFoundError: No module named 'utils.dataloaders'

**Comment by LudvigKnast** [comment]
I have the same problem and as you can see the file is there but still can't be imported, I have made sure to clone the repo correctly and everything else from utils works well... Any thoughts?

![image](https://user-images.githubusercontent.com/95716961/173042184-65dc27f3-fd49-4841-a2d2-b26eb8bfcf0f.png)

**Comment by zohaib-khan5040** [comment]
Just did this and its still giving me the same error
![image](https://user-images.githubusercontent.com/67925902/173569255-fdb789a2-e2fa-424a-8048-5a77d6ead2bc.png)

**Comment by qiaoyukeji** [comment]
我这边也这样报错了， 将报错的 utils.dataloaders 修改为 yolov5.utils.dataloaders ，我这边就可以运行了
